version: "3.8"

networks:
  dapr:
    name: "dapr-net"
  traefik:
    name: "traefik"

services:

  api-gateway:
    image: traefik:v2.3
    networks:
      - traefik
    ports:
      - 80:80
      - 8080:8080 # if you enabled the dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--entrypoints.http.address=:80"
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"

  fake-orders:
    image: localhost:5000/br1cascio/fake-orders-service
    network_mode: host
    command: --app-id orders-service --dapr-http-port 3500 --app-port 3000 npm start
    networks:
      - traefik
      - dapr
    volumes:
      - ./apps/fake-orders-service/index.js:/app/index.js
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.routers.orders-service.rule=Host(`api.0.0.0.0.sslip.io`)"
        - "traefik.http.routers.orders-service.entrypoints=http"
        - "traefik.http.middlewares.api-entrypoint.addprefix.prefix=/v1.0/invoke/orders-service/method"
        - "traefik.http.routers.orders-service.middlewares=api-entrypoint"
        - "traefik.http.services.orders-service.loadbalancer.server.port=3500"

  fake-users:
    image: localhost:5000/br1cascio/fake-users-service
    network_mode: host
    command: --app-id users-service --dapr-http-port 3500 --app-port 3000 npm start
    networks:
      - dapr
    volumes:
      - ./apps/fake-users-service/index.js:/app/index.js

  fake-products:
    image: localhost:5000/br1cascio/fake-products-service
    network_mode: host
    command: --app-id products-service --dapr-http-port 3500 --app-port 3000 npm start
    networks:
      - dapr
    volumes:
      - ./apps/fake-products-service/index.js:/app/index.js