version: "3"

networks:
  dapr_example:
    driver: weave:latest
    
services:
  redis:
    image: redis:alpine
    networks:
      - dapr_example

  nodeapp:
    image: localhost:5000/dapr-nodeapp:dev
    networks:
      - dapr_example
    environment:
      DAPR_APP_ID: nodeapp
      DAPR_LOG_LEVEL: debug

  pythonapp:
    image: localhost:5000/dapr-pythonapp:dev
    networks:
      - dapr_example

  placement:
    image: daprio/placement:${DAPR_VERSION}
    networks:
      - dapr_example
    command: ["./placement", "-port", "50005"]
